# Generated by Django 4.0.3 on 2022-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_log_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
