version: '3.8'

services:
  api:
    build: ./caseLog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./caseLog:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - REDIS_HOST=redis://redis
    links:
      - db:db
    depends_on:
      - db
      - redis
    networks:
      - djangonetwork

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASS=postgres
    networks:
      - djangonetwork

  redis:
    image: "redis:6.2.6-bullseye"
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
    djangonetwork:
        driver: bridge
